### ISSUE TITLE
Adding product to cart when shipping profile doesnt exists

### ISSUE THREAD

**Issue by Hesesses** [jonassiewertsen/statamic-butik#101]
I have a product which have shipping profile "test"
I delete the shipping profile "test" and add the product to cart

When going to cart page I get an error:

```
TypeError
Argument 1 passed to Jonassiewertsen\StatamicButik\Shipping\Shipping::detectShippingZone() must be an instance of Jonassiewertsen\StatamicButik\Http\Models\ShippingProfile, null given, called in /vendor/jonassiewertsen/statamic-butik/src/Shipping/Shipping.php on line 50
```

I think it should display an error instead of 500 or even better, you cant delete shipping profile if its already used in any product

**Comment by jonassiewertsen** [comment]
I will build a checkt that you can't delete the shipping zone if products are assigned.
