### ISSUE TITLE
Refresh loop after payment

### ISSUE THREAD

**Issue by Hesesses** [jonassiewertsen/statamic-butik#106]
After succesful payment butik shows the receipt, but the page is refreshed every few seconds until "This link is not valid anymore."

I was expecting the page to not refresh

**Comment by jonassiewertsen** [comment]
This is the expected behavior, because the payment status may change after you visit the page. 

That's because of the reason, that we are using webhooks. 

To avoid the refresh, we could add a button which says refresh and won't do it automatically.

**Comment by jonassiewertsen** [comment]
I will remove this behavior in the next release.
