### ISSUE TITLE
In case of invalid form fields, the form won't give any feedback. 

### ISSUE THREAD

**Issue by jonassiewertsen** [jonassiewertsen/statamic-butik#112]
This is a Statamic problem. 

```
{{ if {error:mail} }}
``` 

This therm should be true, but is not.

**Comment by jonassiewertsen** [comment]
Related to https://github.com/statamic/cms/issues/2456

**Comment by jonassiewertsen** [comment]
This should be resolve with Statamiv version 3.0.19

Any Feedback if it's working again?

**Comment by jonassiewertsen** [comment]
This seems not to be resolved.

**Comment by philipboomy** [comment]
I just saw this now. I have done a PR which fixes this issue.
