### ISSUE TITLE
Control Panel permissions

### ISSUE THREAD

**Issue by Hesesses** [jonassiewertsen/statamic-butik#119]
I have created a new user with role/permissions:

![image](https://user-images.githubusercontent.com/2721970/95946586-8685db00-0df5-11eb-83db-04796ef2e883.png)

When the user logins, the butik settings is displayed on the left
![image](https://user-images.githubusercontent.com/2721970/95946662-b208c580-0df5-11eb-97f2-e32e8ce35ccb.png)

Clicking Shipping or Taxes gives an error, but would be better to hide the whole settings menu

**Comment by jonassiewertsen** [comment]
Good catch!

Will be solved in the next release.
