### ISSUE TITLE
Show price without TAX

### ISSUE THREAD

**Issue by Hesesses** [jonassiewertsen/statamic-butik#124]
Hello,

Would be nice to have a helper to display price without TAX.

For example product price is 100 and tax is 20%

`{{ price }}` would display 100
and
`{{ price_without_tax }}` would display 80

Why?
Many stores which targets to companies usually displays their pricing without taxes and the taxes are only shown on checkout

**Comment by jonassiewertsen** [comment]
I agree!

It's already present in the controller, so it will be a fast and useful implementation.
