### ISSUE TITLE
Decrease quality in basket goes to 0 if stock is 0 despite unlimited stock

### ISSUE THREAD

**Issue by philipboomy** [jonassiewertsen/statamic-butik#130]
If stock is unlimited but stock quality is 0 then the decrease does not working proper. See example here: https://share.getcloudapp.com/qGuvnxdO - Goes to 0 instantly despite having 4 or 5 qty in the basket.

Kind of related issue here: #107

**Comment by jonassiewertsen** [comment]
Thanks for the video! That did help a lot.
