### ISSUE TITLE
Missing :mail value in the order box on the receipt page

### ISSUE THREAD

**Issue by wautersj** [jonassiewertsen/statamic-butik#140]
On the receipt page, in the order box, it reads: 
**A confirmation email will be sent to :mail**

It does not fill in the customers email, it just shows ':mail'.
Probably an issue with how it's passed to the translation?

---

Great work with Butik!

**Comment by jonassiewertsen** [comment]
Which version of butik are you using?

Did you publish the translation files?

Can you check for me, if your translation file and this line are the same?

Thanks,
Jonas

**Comment by leganz** [comment]
This is already fixed with https://github.com/jonassiewertsen/statamic-butik/pull/139

**Comment by jonassiewertsen** [comment]
It has been fixed, but in case the translation files have been updated, you need to change the following line manually.

https://github.com/jonassiewertsen/statamic-butik/blob/master/resources/lang/en/web.php#L33
