### ISSUE TITLE
A total order above €1000 results in a Mollie error when initiating payment

### ISSUE THREAD

**Issue by wautersj** [jonassiewertsen/statamic-butik#144]
I added several items to my shopping bag, exceeding a total of €1000.

When I then go to payment (redirected to mollie) I get an error: 

![Schermafbeelding 2020-12-01 om 14 10 33](https://user-images.githubusercontent.com/4070167/100745245-47303f80-33df-11eb-8303-1b3fcc1ea3f9.png)

From what I understand, the value passed to Mollie is formatted (or not formatted. I don't know in which format Mollie expects the the value to be), and is therefor invalid, for Mollie to process.

**Comment by wautersj** [comment]
I see the ticket is closed. Can we expect a release of Butik, where this is fixed, soon?

**Comment by jonassiewertsen** [comment]
I fixed it yesterday in this version:
https://github.com/jonassiewertsen/statamic-butik/releases/tag/v3.2.4

Please let me know if you still run into this issue.

**Comment by wautersj** [comment]
Ah I see, I've done the update, thanks!

**Comment by jonassiewertsen** [comment]
Good to hear 💯
