### ISSUE TITLE
Submission of a contact form is validated as an order

### ISSUE THREAD

**Issue by wautersj** [jonassiewertsen/statamic-butik#145]
I've created a "Contact" page with a Statamic form on it.

When the form is submitted, it looks like it is validated as an order, some extra logic from Butik to handle orders. 

Ofcourse this should not pass by this logic :) 

Currently it throws an error, because order fields are not present in my contact form: 

![Schermafbeelding 2020-12-01 om 16 13 02](https://user-images.githubusercontent.com/4070167/100759111-8adf7500-33f0-11eb-8832-ea8166b194c7.png)

![Schermafbeelding 2020-12-01 om 16 16 26](https://user-images.githubusercontent.com/4070167/100759167-99c62780-33f0-11eb-9e74-fd36a789f6e9.png)

**Comment by jonassiewertsen** [comment]
Good find. Thanks!

I will dig into it. It does like the event will be handled, but it shouldn't.

**Comment by wautersj** [comment]
I see the ticket is closed. Can we expect a release of Butik, where this is fixed, soon?

**Comment by wautersj** [comment]
Update: I see it is fixed in the latest version! Thanks!

**Comment by jonassiewertsen** [comment]
Sorry, I could have written it more clearly. My fault.
