### ISSUE TITLE
Accessing customer data in the 2 emails

### ISSUE THREAD

**Issue by wautersj** [jonassiewertsen/statamic-butik#146]
I'm trying to access some customer data to use in the emails:
(Customer data, as in the form that is filled in and submitted)

I'm talking about: 
- orderConfirmationToSeller.blade.php
- purchaseConfirmationForCustomer.blade.php

I've added a field to the checkout form, being "delivery_day", now i'm trying to find a way to render it in the email.

(To my understanding the fields submitted in the form are part of 'customer'. It has been used like this in other places too.)

My attempts so far: 

<img width="612" alt="Schermafbeelding 2020-12-02 om 13 11 46" src="https://user-images.githubusercontent.com/4070167/100871083-f59bb980-349f-11eb-9110-0fd760d888e9.png">

What syntax/code can I use to access these customer fields in the email?
_(firstname, surname, email, ..., delivery_day)_

**Comment by jonassiewertsen** [comment]
This looks right to me, but let me check that and I will get back to you in the next couple of days (and updated docs).

**Comment by wautersj** [comment]
Some extra info:

It looks like the second works for me:   $order->customer->delivery_day

But it only works for the orderConfirmationToSeller.

<img width="602" alt="Schermafbeelding 2020-12-02 om 13 03 11" src="https://user-images.githubusercontent.com/4070167/100875423-47dfd900-34a6-11eb-9379-1f36e18f1e4f.png">

I don't get any value for the purchaseConfirmationForCustomer

<img width="700" alt="Schermafbeelding 2020-12-02 om 13 04 11" src="https://user-images.githubusercontent.com/4070167/100875453-4f9f7d80-34a6-11eb-9764-b7af1690c211.png">

**Comment by wautersj** [comment]
If I can get the same context concerning the customer, in the purchaseConfirmationForCustomer blade, 
that would be a good solution for me.

being:  $order->customer

You you have an idea of when you might be able to look in to this?

The shop we're building should go live tomorrow evening. I could push it an extra day...
It would be of great help If we could find a solution for this! 

Thanks in advance!

**Comment by wautersj** [comment]
I've pinpointed why it works for the seller mail, but not the customer mail:

A. In one file the var is protected, in the other the var is public:
B. There is a class variable $order, but also a __construct parameter $order. This might be conflicting for scoping?

<img width="597" alt="Schermafbeelding 2020-12-02 om 15 28 07" src="https://user-images.githubusercontent.com/4070167/100885703-3e10a280-34b3-11eb-836c-b0526fc7604f.png">

<img width="680" alt="Schermafbeelding 2020-12-02 om 15 28 14" src="https://user-images.githubusercontent.com/4070167/100885721-423cc000-34b3-11eb-8516-42f7a38dcace.png">

A quick solution for today, would be to make the protected variable public ?

**Comment by jonassiewertsen** [comment]
Will be fixed in the next release.

**Comment by jonassiewertsen** [comment]
I wasn't happy with the solution and did revert some of it, to avoid breaking changes later. 

https://github.com/jonassiewertsen/statamic-butik/releases/tag/v3.2.6

You can reach the customer through the `$order`, so it solve your problem for now @wautersj.
As well I can implement it properly without any breaking changes later. 

This issue will stay open, until I got this implement correctly.

**Comment by wautersj** [comment]
@jonassiewertsen Yes! This is oké for now, thanks!

I doubt exposing the customer as a direct variable to the view would break anything. 
It just adds another layer; to my understanding. 

Kind of a shorthand ($customer) for $order->customer.

If you have an alternative way or other implementation, keep me posted. I'm interested! 

Thanks for the speedy feedback

**Comment by jonassiewertsen** [comment]
Customer information will be available with the next release, as described here:
https://www.butik.dev/frontend/mailables
