### ISSUE TITLE
Bug with variation product in cart when stock_unlimited is managed at variation level

### ISSUE THREAD

**Issue by wautersj** [jonassiewertsen/statamic-butik#152]
**Case 1:** 
- 'Stock Unlimited' is set on the main product level
- 'Inherit Stock' is selected at the variations level

**Case 1 - Result:** 
This works fine! Everything displays normal on the cart page.

- - - 

**Case 2:** 
- 'Stock Unlimited' is set on the main product level
- 'Stock Unlimited' is selected at the variations level

**Case 2 - Result:** 
When navigating to the cart, the user gets an error. Cfr screenshot: 

(this happens when I add items to my cart, which are configured like Case 2, and then try to access the cart page)

<img width="1101" alt="Schermafbeelding 2020-12-08 om 11 51 10" src="https://user-images.githubusercontent.com/4070167/101476847-a564a180-394e-11eb-9232-b1f52f3915d9.png">

**Comment by jonassiewertsen** [comment]
Can you reproduce this bug after removing all of your active sessions from `storage/framework/sessions`?

**Comment by wautersj** [comment]
@jonassiewertsen I will try this as soon as possible, and will get back to you.
But is seems to be persistent.

**Comment by jonassiewertsen** [comment]
Please let me know in case it appears again. 

I am having a hard time reproducing this bug and will reopen this issue if there is more information to dig into.
