### ISSUE TITLE
Mollie doesn't operate for USA vendors

### ISSUE THREAD

**Issue by nn-dmt** [jonassiewertsen/statamic-butik#161]
I am forced to use either Stripe or Paypal because i'm in the USA.

I am not a php developer and so the documentation provided does not do me any good - it talks like a lot of assumptions made that I'm already very well versed in php/laravel developer - I am someone who is coming from html/css/wordpress and trying to make a working site that i can very easily make in wordpress/woocommerce but in an alternative way 'from scratch'

Is stripe / paypal payment gateways on your roadmap? How much money could I offer you to speed it up or get it going? I'm not looking to learn how to configure my server, i want to sell some products. As a business owner more than a developer, I want to pay an expert to make something properly in absence of my own ability, because i'd rather not build some security flaw into my site by not doing things properly. I may have some development skills but I am foremost a business owner and my concerns outweigh my curiosities.

**Comment by jonassiewertsen** [comment]
Thanks for your feedback!

Stripe is on the roadmap and I hope to add it soon, but I can't name a specific date or deadline.

I am closing this issue in favor of the idea I did open for you: https://github.com/jonassiewertsen/statamic-butik/discussions/163
