### ISSUE TITLE
Tax rate tool does not work at all for USA states

### ISSUE THREAD

**Issue by nn-dmt** [jonassiewertsen/statamic-butik#162]
Hi there,

It seems like more and more Butik is completely not meant for Americans and was built only for European stores...

You can only select one tax rate on product.... in order for this to be useful to Americans, the tax rate needs to be tied to the shipping location and update accordingly based on each individual US State, who each have their own tax rates/laws.

I can only setup a general 'Maximum possible' tax on the products, but that would set the tax of each product over 8.75% when some states have ZERO tax, and most states have 7.

**Comment by jonassiewertsen** [comment]
It has been developed in Europe, yes :-)

I am open to suggestions, so I did open a discussion for it here: https://github.com/jonassiewertsen/statamic-butik/discussions/164

It's not on the roadmap right now. I would love to hear in the discussion, how big of an issue this is for a general shop owner in the US.
