### ISSUE TITLE
If not super admin => server 500

### ISSUE THREAD

**Issue by leganz** [jonassiewertsen/statamic-butik#179]
If you create a role with all permissions for butik and it isn't a super admin the server will throw an exception

````
Argument 1 passed to Jonassiewertsen\\StatamicButik\\Policies\\OrderPolicy::index() must be an instance of Statamic\\Auth\\User, instance of App\\Models\\User given
````

Is there a way to specify which user should be check?

**Comment by leganz** [comment]
The latest available. I am using the db for user management ("default laravel one") -> followed the official guide for that

**Comment by jonassiewertsen** [comment]
If using a db for user management, we need to use a different approach. 

As I can see, the Policies in Statamic has been updated as well. I did refactor them by adapting the actual Statamic use of policies. Should be fixed with the next release.
