### ISSUE TITLE
Datatable: Re-appear of removed column

### ISSUE THREAD

**Issue by leganz** [jonassiewertsen/statamic-butik#181]
Butik 3.4.0
Latest statamic

First of all => i love the new datatable.
But i found an issue. If you remove a column and "save" the settings, the removed column will appear again.

![Bildschirmfoto 2021-01-13 um 23 26 48](https://user-images.githubusercontent.com/3373530/104518062-62ee4e80-55f7-11eb-877e-b3ce7430bd59.png)

**Comment by jonassiewertsen** [comment]
Good find!

You are right, those settings do not apply after saving.
