### ISSUE TITLE
Can not toggle toggle visiblility of category in edit view

### ISSUE THREAD

**Issue by freshface** [jonassiewertsen/statamic-butik#188]
## Describe the bug
Can not toggle toggle visiblility of category in edit view

## How to reproduce
1. Add a category
2. edit the category
3. try to toggle the toggle button

## Expected behavior
Cannot toggle it

## Screenshots

<img width="1322" alt="Screenshot 2021-01-29 at 21 08 55" src="https://user-images.githubusercontent.com/103913/106322529-3f253c80-6276-11eb-952e-15e1a37355b4.png">

## Environment

Latest version of statamic and boutik atm

**Comment by jonassiewertsen** [comment]
Thanks for the report. It's right that you can't toggle it. 

After some more digging into the functionality, I did not see any functionality behind the is_visible state. It's saved in the database, but not used anywhere. 

With the knowledge that categories will work differently with butik version 4.0, I did hide the button for now. Why having it, if it's not connected to anything?
I'd rather keep it as it is for now and focus on improvements in version 4 with categories, than reworking it to throw it out the window soon. 

I hope that's all right with you. Let me know if you disagree or if I did miss something.
