### ISSUE TITLE
Route [butik.shop.product] not defined.

### ISSUE THREAD

**Issue by philipboomy** [jonassiewertsen/statamic-butik#192]
## Describe the bug
When adding to cart using the lirewire component I am getting this error: Route [butik.shop.product] not defined.

## How to reproduce
Use the repo (before updating Statamic and Livewire) I have invited you to and go this page collection/alder and click "Purchase"
See the error

**Comment by jonassiewertsen** [comment]
This was a good one and is related to the config setting `product_route_active`. If set to false, butik will not create the product route, which has been needed to create the show url for a product.
