### ISSUE TITLE
Livewire bug on latest update

### ISSUE THREAD

**Issue by philipboomy** [jonassiewertsen/statamic-butik#193]
## Describe the bug
Too few arguments to function Illuminate\Support\Str::replaceFirst(), 2 passed in /Users/pat/Sites/xxxxxxx/vendor/livewire/livewire/src/helpers.php on line 12 and exactly 3 expected

## How to reproduce
Visit the website and you will see this error. You can use the repo I invited you to.

## Environment

Statamic 3.0.42 Pro
Laravel 8.26.1
PHP 7.4.14
jonassiewertsen/statamic-butik 3.5.1
jonassiewertsen/statamic-livewire 2.4.0

**Comment by jonassiewertsen** [comment]
I am having a hard time reproducing this issue. 

This does not mean the issue is not there. Can you provide more information to reproduce it?

**Comment by philipboomy** [comment]
If anyone is having this issues then this will fix it.

```
php artisan livewire:publish --config
php artisan config:cache
```

See here for more info https://github.com/livewire/livewire/issues/2447#issuecomment-772520272
