### ISSUE TITLE
Cant delete form entries or users

### ISSUE THREAD

**Issue by philipboomy** [jonassiewertsen/statamic-butik#197]
## Describe the bug
In a fresh install of starter kit and manual install as well I cannot delete users or form entries via the CP. The delete link is gone despite I am a super admin.

## Screenshots
https://share.getcloudapp.com/YEuXbzqx

## Environment

Statamic 3.0.45 Pro
Laravel 8.31.0
PHP 7.4.14
jonassiewertsen/statamic-butik 3.5.3
jonassiewertsen/statamic-livewire 2.4.0

**Comment by jonassiewertsen** [comment]
Thanks for letting me know. 

The 'delete orders' action and the native Statamic 'delete' action are interfering with each other.

**Comment by jonassiewertsen** [comment]
Two things are happening. 

1. By accident I did overwrite the default delete action. This will be resolved by renaming the butik action. 
2. In a none multi-site context the button will appear twice though, because of the following bug: https://github.com/statamic/cms/issues/3174

**Comment by jonassiewertsen** [comment]
What's better? 

1. Should I push a temporary fix (but you would always see two delete buttons. Both will be working. 
2. Wait until the statamic bug has been fixed. I did create a PR for the issue.

**Comment by jonassiewertsen** [comment]
https://github.com/statamic/cms/pull/3351

**Comment by jonassiewertsen** [comment]
https://github.com/statamic/cms/issues/3350

**Comment by jonassiewertsen** [comment]
I did apply a temporary fix to avoid conflicts with the core permissions:
https://github.com/jonassiewertsen/statamic-butik/commit/672585efee56419becd131122a7208542366032d

This is clearly not a good solution:
Both delete buttons do work, but you can't limit the permissions as described in the docs. If you do, there will always be one single button to delete the orders. 

I did PR a possible solution to the core, but we need to wait if this is a good solution and if I didn't miss anything:
https://github.com/statamic/cms/pull/3351

**Anyways: This does feel like a better solution for now, so butik won't conflict with the Statamic core. I'll keep this issue open to keep track.** 

![Screenshot 2021-03-14 at 17 07 39](https://user-images.githubusercontent.com/38906163/111075324-cdcce080-84e7-11eb-815e-4032082271d3.png)

**Comment by jonassiewertsen** [comment]
This should be resolved by now. Let me now if you gut still got problems!
