### ISSUE TITLE
Taxes with decimals

### ISSUE THREAD

**Issue by rrelmy** [jonassiewertsen/statamic-butik#225]
## Describe the bug
The butik does not play very well with taxes with a decimal (example: 7.7% in [switzerland](https://www.estv.admin.ch/estv/en/home/mehrwertsteuer/fachinformationen/was-ist-die-mehrwertsteuer.html#-1323050223)).
In the cp there is no issue, everything can be created as expected with floats, but in the frontend there are multiple issues (there might be more than I found!)

## How to reproduce
1. Clone the starter kit like documented
2. Set the tax to `7.7`
3. Try to add an item to the basket

### Items can not be added to the basket

> ErrorException: A non well formed numeric value encountered
> vendor/jonassiewertsen/statamic-butik/src/Checkout/Item.php:110

Looks like on this line a `string` is passed into a `float` variable
https://github.com/jonassiewertsen/statamic-butik/blob/e5ff7a9d0ad2a6c1485deafbebcfdb4797e645e8/src/Checkout/Item.php#L110

_Further errors have been found after changing the line to `$this->taxRate = (float) $item->tax->percentage;` so I could continue_

### Return value of Jonassiewertsen\StatamicButik\Shipping\ShippingAmount::taxPercentage() must be of the type int, string returned
Another case that returns float/string instead of int
https://github.com/jonassiewertsen/statamic-butik/blob/e5ff7a9d0ad2a6c1485deafbebcfdb4797e645e8/src/Shipping/ShippingAmount.php#L68

_I did not check the rest of the code!_

### Wrong tax percentage displayed in cart (Might be an issue in the starter kit and not the addon)

Only `7` instead of `7.7` is displayed
<img width="509" alt="Statamic" src="https://user-images.githubusercontent.com/442683/118531608-4fd6c100-b746-11eb-84fb-6c40301b715c.png">

### Tax calculation is based on the int value instead of float

€ 192,00 VAT displayed € 12,56
Expected 13.73 (if I didn't made a mistake, 192-(192/107.7*100))

## Expected behavior
It should just work :shrug:

## Environment
Statamic 3.0.49 Solo
Laravel 8.41.0
PHP 7.4.16
jonassiewertsen/statamic-butik 3.5.5
jonassiewertsen/statamic-livewire 2.5.0

**Comment by rrelmy** [comment]
😕 I can't reproduce the issues after changing the currency to swiss francs and a `.` delimiter
```
    'currency_name'      => 'CHF',
    'currency_isoCode'   => 'CHF', // Make sure to use ISO_4217 https://en.wikipedia.org/wiki/ISO_4217
    'currency_symbol'    => 'CHF',
    'currency_delimiter' => '.',
```

but it shows another issue, multiple taxes even if only one (7.7) is configured
<img width="517" alt="Statamic" src="https://user-images.githubusercontent.com/442683/118534936-2029b800-b74a-11eb-884f-9b4fd7374550.png">

**Comment by jonassiewertsen** [comment]
I'll check for a bugfix. 

Thanks for reaching out.

**Comment by jonassiewertsen** [comment]
I can't reproduce the issue right now. Please reopen in case you will run into this again.
