### ISSUE TITLE
error when looking at the product

### ISSUE THREAD

**Issue by 4kets** [jonassiewertsen/statamic-butik#229]
## Describe the bug
After i create a new product and i look on the frontend on the specific product i get an error.

## How to reproduce
1. Create new product (I have added a screenshot of the product values i have used)
2. Go to the specific product page

## Screenshots
error
![image](https://user-images.githubusercontent.com/20043831/121524735-e4f07100-c9f7-11eb-87b5-3b0f18d79fd5.png)

product info
![image](https://user-images.githubusercontent.com/20043831/121524951-1ec17780-c9f8-11eb-8661-70f5c9245907.png)

**Comment by 4kets** [comment]
Update:

i have found out for a quick fix if you make a variant and remove the variant it works

**Comment by jonassiewertsen** [comment]
I'll release a fix ASAP

**Comment by jonassiewertsen** [comment]
I couldn't recreate the issue. I will reach out to you.

**Comment by jonassiewertsen** [comment]
I could recreate the issue now. There is a collision with the variants Fieldtype. I am on it.

**Comment by jonassiewertsen** [comment]
Please let me know if the latest release does fix your issue:
https://github.com/jonassiewertsen/statamic-butik/releases/tag/v3.5.7
