### ISSUE TITLE
show only the categorie to which the product belongs?

### ISSUE THREAD

**Issue by Oleafeon** [jonassiewertsen/statamic-butik#234]
Right now when i give a product a categorie i can not add that categorie to the product page it will return al the categories that exist, I want to only show the categorie to which the product belongs?

**Comment by jonassiewertsen** [comment]
Thanks! 

I'll add this to the product tag.

**Comment by jonassiewertsen** [comment]
@Oleafeon it has been added in the last version https://github.com/jonassiewertsen/statamic-butik/releases/tag/v3.6.0
