### ISSUE TITLE
Add Information to include livewire scripts into layout.

### ISSUE THREAD

**Issue by Oleafeon** [jonassiewertsen/statamic-butik#235]
## Describe the bug
i have a problem that when i setup the buttons via
```
<button wire:click="add()" class="btn btn-shop">
    <i class="fas fa-shopping-cart"></i> {{ 'butik::web.add_to_bag' | trans }}
</button>
```
or even
`{{ livewire:butik.add-to-cart slug="{{ slug }}" }}`
the button not work
it wont place my items in the cart

**Comment by Oleafeon** [comment]
this is fixed i had to include {{ livewire:scripts }} in layout

**Comment by jonassiewertsen** [comment]
As it does work with Livewire, you need to include the livewire scripts.

Glad you got it working already!

**Comment by Oleafeon** [comment]
Maybe you should include it in the docs 😄

**Comment by jonassiewertsen** [comment]
I thought I already had, but is missing. 

I will add it.

**Comment by jonassiewertsen** [comment]
Thanks for letting me know @Oleafeon 

It might not be perfect but should help clearing things up. Let me know if something else is missing.

https://www.butik.dev/frontend/livewire
