### ISSUE TITLE
Unused Braintree lib

### ISSUE THREAD

**Issue by jimblue** [jonassiewertsen/statamic-butik#30]
I've notice Braintree is in package.json dependencies here :
https://github.com/jonassiewertsen/statamic-butik/blob/2ae7c5059135236bcd4951ea4924efdb42d7d4d6/package.json#L18

But at the same time it's never used in the resources.

**Comment by jonassiewertsen** [comment]
You're right, that shouldn't bee there anymore. 

I am working really hard von version 2 at the moment and will remove it with the next version.

Thank you!
