### ISSUE TITLE
Create a products fieldtype, so products can be inserted anywhere on the page

### ISSUE THREAD

**Issue by jonassiewertsen** [jonassiewertsen/statamic-butik#61]
This would make it possible, to add products anywhere on your page. 

That might be a good feature for story stelling and inserting products inside of your blog or anywhere you want.

**Comment by Hesesses** [comment]
Isnt this already implemented when the products are statamic collection?

**Comment by jonassiewertsen** [comment]
Yes, with the new changes in version 3 there are. 

Thanks.
