### ISSUE TITLE
Payment processing with Mollie

### ISSUE THREAD

**Issue by rcknr** [jonassiewertsen/statamic-butik#71]
After testing payments with Mollie I have noticed that a customer is created for every payment which results in duplicate entries for the same name/email and is not re-used afterwards. Mollie API, however, doesn't allow for easy retrieval of a customer by email. The only way to do it is to list all customers, look for an email and paginate, which is also not very effective.
What could be beneficial though is to use Mollie's Orders API as a backend for payments, orders, and storing customers info.
This will result in vendor locking to Mollie, which could be a problem. But then again, seeing no other payment gateway support and complexity of adding one (e.g. Stripe) could just lead to conclude that locking to Mollie might be a wise design choice.
I would be interested in getting opinions on this matter.

**Comment by jonassiewertsen** [comment]
Actually there is no need to create a single for every payment. In our case, without a user login and without recurring payments, it does actually not make sense to do so. 

I will remove the user creation from the payment gateway. 

Good find!

**Comment by jonassiewertsen** [comment]
The payment process has been refactored. 

Besides the refactor I did change from the Mollie Payment API to the Mollie Orders API. 
This will open up for the use of Klarna Payments, partial shipping etc. 

Closed via https://github.com/jonassiewertsen/statamic-butik/commit/3e27d0ee61c5a9e78feeab596191bb3a3c3362a4
