### ISSUE TITLE
We need a way to add additional product information

### ISSUE THREAD

**Issue by jonassiewertsen** [jonassiewertsen/statamic-butik#80]

**Comment by octoper** [comment]
I think the easier way to do this is to move to Statamic Collections instead of database.

**Comment by jonassiewertsen** [comment]
Thanks for your feedback @octoper !

Statamic Collections would be the easiest option for exactly this case. You are right.
In a lot of other cases butik does handle, I do prefer SQLite a lot though. Using SQLite is a decision made after a lot of trying, thinking and tinkering around. 

Unfortunately, there is no perfect solution to all problems with either Statamic Collections or SQLite or MySQL. 

I might have found a really nice solution, but will tinker a little more with it. Either way, it will be a SQLite solution, which is the core of butik and can't be changed that easily.

There are people out there, preferring my SQLite solution for butik, others don't like that decision. That's regrettably the way it is and there is no way to make to make everybody happy. 
We'll soon see a solution. 

Thanks again for your opinion.
