### ISSUE TITLE
Could you please add the possibility to pay by bill?

### ISSUE THREAD

**Issue by j3ll3yfi5h** [jonassiewertsen/statamic-butik#85]

**Comment by jonassiewertsen** [comment]
This is a great idea!

Could you add it here to ideas, so we can keep zrack of it?

https://feedback.userreport.com/81c07a00-5ad7-4f63-b28d-503c3a76bfdc/#ideas/popular

**Comment by jonassiewertsen** [comment]
Thanks for adding the idea @j3ll3yfi5h ! 

I will look into it and closes this issue for now.

**Comment by jonassiewertsen** [comment]
@j3ll3yfi5h I am not sure how fast and if it will be integrated into the core. 

Would it help if there would be added more events, so you could extend the order form as you need it and check if the customer does want to pay via bill instead.
The event would make it possible to extend Butik and redirect to mollie in that case. It would make your wish possible, but you need to extend it yourself.

If adding the event, I would help you pointing into the right direction. 

Let me know what you think :-)

**Comment by j3ll3yfi5h** [comment]
@jonassiewertsen Thank you for the reply and the inputs. Unfortunately with the current project we don't have time and budget to extend this functionality by ourself, especially when there is already a license fee.

With another project I'll maybe come back to your help and l'll have another go with Butik.
